version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=dss_db
      - DB_USER=usuario
      - DB_PASSWORD=clave

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dss_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
